name: Publish Docker container to GHCR

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: repo_owner
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository_owner }}

      - name: Set IMAGE_TAGS variable
        run: |
          echo "IMAGE_TAGS=ghcr.io/${{ steps.repo_owner.outputs.lowercase }}/contenttruck:${{ github.sha }}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Add additional image tags for release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "IMAGE_TAGS=${IMAGE_TAGS},ghcr.io/${{ steps.repo_owner.outputs.lowercase }}/contenttruck:${{ github.event.release.tag_name }},ghcr.io/${{ steps.repo_owner.outputs.lowercase }}/contenttruck:latest" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAGS }}
          platforms: linux/amd64,linux/arm64
